name: Run Instagram Chatbot

on:
  push:
    branches:
      - main

jobs:
  run-chatbot:
    runs-on: ubuntu-latest

    steps:
      # الخطوة 1: سحب الكود من المستودع
      - name: Checkout code
        uses: actions/checkout@v3

      # الخطوة 2: إعداد Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # الخطوة 3: تثبيت المتطلبات
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai requests

      # الخطوة 4: تشغيل السكربت
      - name: Run chatbot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
          INSTAGRAM_BUSINESS_ID: ${{ secrets.INSTAGRAM_BUSINESS_ID }}
        run: |
          python instagram_chatbot.py
