name: Instagram Chatbot

on:
  push:
    branches:
      - main  # يتم تشغيله عند الدفع إلى الفرع الرئيسي
  workflow_dispatch:  # يتيح تشغيل الـ Action يدويًا عبر واجهة GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest  # يعمل على أحدث بيئة من Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # تحميل المستودع

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # تحديد نسخة Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai requests

      - name: Run Instagram Chatbot
        run: |
          python -c "
import requests
import openai
import time

# إعدادات OpenAI
openai.api_key = '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'

# إعدادات Instagram
PAGE_ACCESS_TOKEN = 'EAANWqohOJlsBO6ZCUVlokCDvkZB1IwWpjrefcJpdHCou8ZAZALtO5c3VB1ZBKSaZCWZAgklUtRdav6ve6ULta6LrheCLNZB7z18iZANMDlv51HXvApmeQjx26ZApOrnh38Fgkk1zy1ZA8jJzbv65OnH4wlmvJBvcMb5nMMpccZC4ZAtebMuOqdel0OWqW6zZAqcajMwCkkwj7fXGhEJbmuKqIVgYiyshveyDEZD'
INSTAGRAM_BUSINESS_ID = '1316744332839871'

def get_chatgpt_response(user_message):
    # استدعاء GPT-3 للحصول على رد على الرسالة
    response = openai.Completion.create(
        engine='text-davinci-003',  # يمكنك استخدام gpt-3.5-turbo أيضًا
        prompt=user_message,
        max_tokens=150
    )
    return response.choices[0].text.strip()

def get_messages():
    # الحصول على رسائل جديدة عبر Instagram API
    url = f'https://graph.facebook.com/v17.0/{INSTAGRAM_BUSINESS_ID}/inbox'
    params = {
        'access_token': PAGE_ACCESS_TOKEN
    }
    response = requests.get(url, params=params)
    messages = response.json()

    if 'data' in messages:
        return messages['data']
    return []

def send_message(recipient_id, text):
    # إرسال الرد إلى المستخدم
    url = f'https://graph.facebook.com/v17.0/me/messages'
    headers = {
        'Content-Type': 'application/json'
    }
    payload = {
        'recipient': {'id': recipient_id},
        'message': {'text': text},
        'access_token': PAGE_ACCESS_TOKEN
    }
    response = requests.post(url, json=payload, headers=headers)
    if response.status_code == 200:
        print('تم إرسال الرسالة بنجاح!')
    else:
        print('حدث خطأ في إرسال الرسالة:', response.text)

def main():
    print('البوت يعمل...')
    while True:
        messages = get_messages()
        for message in messages:
            if 'message' in message:
                sender_id = message['from']['id']
                user_message = message['message']['text']
                print(f'رسالة جديدة من {sender_id}: {user_message}')

                # الحصول على رد من GPT-3
                bot_reply = get_chatgpt_response(user_message)

                # إرسال الرد إلى المستخدم
                send_message(sender_id, bot_reply)

        time.sleep(5)  # الانتظار 5 ثواني قبل التحقق من الرسائل الجديدة

if __name__ == '__main__':
    main()
          "
